#!/usr/bin/env python
"""Generate the reference section of the docs site from its two sources.

Every page this writes restates facts that already exist in machine-readable
form — the OpenAPI schema, the Typer command tree, ``Settings.from_environment``
and each role's ``argument_specs.yml``. Generating them means they cannot drift;
``--check`` fails CI when the committed output no longer matches those sources.

Both sources live in other repositories, so this documents whichever versions
are installed:

* the control plane comes from the installed ``blitzecdn`` distribution
  (``requirements.txt``);
* the edge roles come from the installed ``blitzecdn.edge`` collection
  (``requirements.yml``).

Point ``BLITZECDN_EDGE_COLLECTION`` at a checkout to preview unreleased role
changes. A sibling ``../blitze-cdn-edge`` checkout is picked up automatically
as a development convenience.

Nothing here may read real controller state. The API generator builds the app
against a throwaway ``Settings`` in a temporary directory, because
``create_app()`` with no arguments would call ``Settings.from_environment()``
and open the operator's real SQLite database as a side effect.
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import tempfile
from pathlib import Path
from typing import Any

import yaml

WEB_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = WEB_DIR / "src/content/reference"

BANNER = (
    "{/* Generated by scripts/generate_reference.py. Do not edit by hand;\n"
    "    run `npm run generate` after upgrading blitzecdn or blitzecdn.edge. */}\n"
)


def _control_plane_source() -> Path:
    """Locate config.py in the installed control plane, for the AST walk."""
    from blitzecdn import config

    return Path(config.__file__)


def _edge_roles_dir() -> Path:
    """Locate roles/ of the edge collection this site documents."""
    override = os.environ.get("BLITZECDN_EDGE_COLLECTION")
    candidates = [Path(override)] if override else []
    candidates += [
        WEB_DIR / ".state/collections/ansible_collections/blitzecdn/edge",
        Path.home() / ".ansible/collections/ansible_collections/blitzecdn/edge",
        Path("/usr/share/ansible/collections/ansible_collections/blitzecdn/edge"),
        # Development convenience: a sibling checkout of the edge repository.
        WEB_DIR.parent / "blitze-cdn-edge",
    ]
    for candidate in candidates:
        if (candidate / "roles").is_dir():
            return candidate / "roles"
    raise SystemExit(
        "Cannot find the blitzecdn.edge collection. Install it with\n"
        "  ansible-galaxy collection install -r requirements.yml "
        "-p .state/collections\n"
        "or set BLITZECDN_EDGE_COLLECTION to a checkout."
    )


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------


def _text(value: object) -> str:
    """Escape free prose for MDX.

    MDX reads `{...}` as a JavaScript expression and `<` as a JSX tag, so a
    docstring mentioning `/v1/deployments/{id}` becomes `id is not defined` at
    build time. Values rendered inside backticks by `_cell` are already safe.
    """
    if value is None:
        return ""
    return (
        str(value)
        .replace("{", "\\{")
        .replace("}", "\\}")
        .replace("<", "\\<")
    )


def _cell(value: object) -> str:
    """Render a value for a Markdown table cell."""
    if value is None or value == "":
        return "—"
    if isinstance(value, bool):
        return "`true`" if value else "`false`"
    if isinstance(value, (list, tuple)):
        return ", ".join(f"`{item}`" for item in value) if value else "—"
    text = str(value).replace("|", "\\|").replace("\n", " ")
    return f"`{text}`"


def _table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return "_None._\n"
    out = ["| " + " | ".join(headers) + " |"]
    out.append("| " + " | ".join("---" for _ in headers) + " |")
    out.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(out) + "\n"


def _schema_name(schema: dict[str, Any]) -> str:
    """Best-effort one-line type description for an OpenAPI schema node."""
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " \\| ".join(_schema_name(item) for item in schema["anyOf"])
    if "allOf" in schema:
        return " & ".join(_schema_name(item) for item in schema["allOf"])
    kind = schema.get("type", "object")
    if kind == "array":
        return f"{_schema_name(schema.get('items', {}))}[]"
    if "enum" in schema:
        return " \\| ".join(json.dumps(value) for value in schema["enum"])
    return str(kind)


# --------------------------------------------------------------------------
# API reference
# --------------------------------------------------------------------------


def build_openapi_schema() -> dict[str, Any]:
    """Build the app against throwaway settings and return its schema."""
    from blitzecdn.api import create_app
    from blitzecdn.config import Settings

    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        ansible = root / "ansible"
        (ansible / "playbooks").mkdir(parents=True)
        state = root / "state"
        settings = Settings(
            project_dir=root,
            state_dir=state,
            database_path=state / "control-plane.db",
            ansible_dir=ansible,
            inventory_path=ansible / "inventory/hosts.yml",
            playbook_path=ansible / "playbooks/edge.yml",
            generated_vars_path=state / "desired-state.yml",
            deployment_lock_path=state / "deployment.lock",
            certificate_dir=state / "certificates",
            acme_challenge_playbook_path=ansible / "playbooks/acme-challenge.yml",
        )
        return create_app(settings).openapi()


def render_api(schema: dict[str, Any]) -> str:
    lines = [
        BANNER,
        "# HTTP API",
        "",
        f"Generated from the OpenAPI schema of `{schema['info']['title']}` "
        f"v{schema['info']['version']}.",
        "",
        "Every route below except `GET /health` requires the `X-API-Key` header.",
        "Ten failed authentications from one client address within a minute return",
        "`429`. Deployment and rollback routes return `202 Accepted` with a queued",
        "record; poll `GET /v1/deployments/{id}` for the outcome.",
        "",
    ]

    for path, operations in sorted(schema.get("paths", {}).items()):
        for method, operation in sorted(operations.items()):
            lines.append(f"## `{method.upper()} {path}`")
            lines.append("")
            summary = operation.get("summary")
            description = operation.get("description")
            if description:
                lines.extend([_text(description), ""])
            elif summary:
                lines.extend([_text(summary), ""])

            parameters = operation.get("parameters", [])
            if parameters:
                rows = [
                    [
                        _cell(item.get("name")),
                        _cell(item.get("in")),
                        _cell(item.get("required", False)),
                        _cell(_schema_name(item.get("schema", {}))),
                        _text(item.get("description")) or "—",
                    ]
                    for item in parameters
                ]
                lines.append("**Parameters**")
                lines.append("")
                lines.append(
                    _table(["Name", "In", "Required", "Type", "Description"], rows)
                )

            body = operation.get("requestBody")
            if body:
                for media, media_type in body.get("content", {}).items():
                    name = _schema_name(media_type.get("schema", {}))
                    required = " (required)" if body.get("required") else ""
                    lines.append(f"**Request body**{required}: `{media}` → `{name}`")
                    lines.append("")

            responses = operation.get("responses", {})
            rows = [
                [
                    _cell(code),
                    _text(response.get("description")) or "—",
                    _cell(
                        _schema_name(
                            response.get("content", {})
                            .get("application/json", {})
                            .get("schema", {})
                        )
                    )
                    if response.get("content")
                    else "—",
                ]
                for code, response in sorted(responses.items())
            ]
            lines.append("**Responses**")
            lines.append("")
            lines.append(_table(["Status", "Description", "Body"], rows))

    schemas = schema.get("components", {}).get("schemas", {})
    if schemas:
        lines.extend(["## Models", ""])
        for name, model in sorted(schemas.items()):
            lines.append(f"### `{name}`")
            lines.append("")
            if model.get("description"):
                lines.extend([_text(model["description"]), ""])
            required = set(model.get("required", []))
            rows = [
                [
                    _cell(field),
                    _cell(_schema_name(definition)),
                    _cell(field in required),
                    _cell(definition.get("default"))
                    if "default" in definition
                    else "—",
                ]
                for field, definition in sorted(model.get("properties", {}).items())
            ]
            lines.append(_table(["Field", "Type", "Required", "Default"], rows))

    return "\n".join(lines)


# --------------------------------------------------------------------------
# CLI reference
# --------------------------------------------------------------------------


def _render_params(params: list[Any]) -> str:
    rows = []
    for param in params:
        if param.name == "help" or getattr(param, "hidden", False):
            continue
        flags = ", ".join(param.opts + param.secondary_opts) or param.name
        default = param.default
        if default in (None, False):
            default = None
        rows.append(
            [
                _cell(flags),
                _cell(getattr(param.type, "name", "text")),
                _cell(bool(param.required)),
                _cell(default),
                _text(getattr(param, "help", None) or "—").replace("\n", " "),
            ]
        )
    return _table(["Flag", "Type", "Required", "Default", "Description"], rows)


def render_cli() -> str:
    import click
    import typer.main

    from blitzecdn.cli import ExitCode, app

    root = typer.main.get_command(app)

    lines = [
        BANNER,
        "# CLI",
        "",
        "Generated from the Typer command tree in `src/blitzecdn/cli.py`.",
        "",
        "## Exit codes",
        "",
        _table(
            ["Code", "Meaning"],
            [[_cell(item.value), item.name.replace("_", " ").title()]
             for item in ExitCode],
        ),
        "## Global options",
        "",
        _render_params(root.params),
    ]

    def emit(command: Any, prefix: str) -> None:
        for name, sub in sorted(getattr(command, "commands", {}).items()):
            full = f"{prefix} {name}".strip()
            lines.append(f"## `{full}`")
            lines.append("")
            helptext = (sub.help or sub.short_help or "").strip()
            if helptext:
                lines.extend([_text(helptext), ""])
            lines.append(_render_params(sub.params))
            if isinstance(sub, click.Group):
                emit(sub, full)

    emit(root, "blitzecdn")
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Configuration reference
# --------------------------------------------------------------------------


def _default_text(node: ast.expr) -> str:
    """Render a default expression from config.py as readable prose."""
    if isinstance(node, ast.Constant):
        return "—" if node.value is None else str(node.value)
    # Defaults are written as `root / 'ansible'` or `state / 'deployment.lock'`.
    if (
        isinstance(node, ast.BinOp)
        and isinstance(node.op, ast.Div)
        and isinstance(node.left, ast.Name)
        and isinstance(node.right, ast.Constant)
    ):
        prefix = {"root": "<project_dir>", "state": "<state_dir>"}.get(
            node.left.id, node.left.id
        )
        return f"{prefix}/{node.right.value}"
    return ast.unparse(node)


def _settings_constraints() -> dict[str, str]:
    from blitzecdn.config import Settings

    constraints: dict[str, str] = {}
    for name, field in Settings.model_fields.items():
        parts = []
        for item in field.metadata:
            for attribute, symbol in (("ge", "≥"), ("le", "≤")):
                if hasattr(item, attribute):
                    parts.append(f"{symbol} {getattr(item, attribute)}")
        if parts:
            constraints[name] = ", ".join(parts)
    return constraints


def render_configuration() -> str:
    """Pair each BLITZE_* variable with its TOML key by parsing config.py."""
    source = _control_plane_source().read_text(encoding="utf-8")
    tree = ast.parse(source)

    settings_class = next(
        node
        for node in tree.body
        if isinstance(node, ast.ClassDef) and node.name == "Settings"
    )

    paired: list[tuple[str, str, str]] = []
    bare: list[str] = []
    for node in ast.walk(settings_class):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        name = getattr(func, "id", None) or getattr(func, "attr", None)
        if name in {"value", "path_value"} and len(node.args) >= 3:
            first, second = node.args[0], node.args[1]
            if isinstance(first, ast.Constant) and isinstance(second, ast.Constant):
                paired.append(
                    (
                        str(first.value),
                        str(second.value),
                        _default_text(node.args[2]),
                    )
                )
        elif (
            name == "get"
            and node.args
            and isinstance(node.args[0], ast.Constant)
            and str(node.args[0].value).startswith("BLITZE_")
        ):
            bare.append(str(node.args[0].value))

    constraints = _settings_constraints()
    rows = [
        [
            _cell(env),
            _cell(f"[blitzecdn].{toml_key}"),
            _cell(default) if default != "—" else "—",
            constraints.get(toml_key, "—"),
        ]
        for env, toml_key, default in sorted(set(paired))
    ]
    # Secrets get their own table below; do not repeat them.
    documented = {env for env, _, _ in paired} | {"BLITZE_API_KEY", "BLITZE_API_KEYS"}

    lines = [
        BANNER,
        "# Configuration",
        "",
        "Generated by parsing `Settings.from_environment` in",
        "`src/blitzecdn/config.py`, so this table cannot drift from the code that",
        "reads it.",
        "",
        "Precedence: environment variable, then the matching key in",
        "`blitzecdn.toml`, then the default. Relative paths resolve against",
        "`BLITZE_PROJECT_DIR` (default: the working directory).",
        "",
        "## Settings",
        "",
        _table(["Environment variable", "TOML key", "Default", "Constraints"], rows),
        "## Secrets",
        "",
        "Secrets are deliberately not valid TOML keys — they are environment-only.",
        "",
        _table(
            ["Environment variable", "Notes"],
            [
                [
                    "`BLITZE_API_KEYS`",
                    "Comma-separated `operator:secret`. Each secret needs ≥ 32 "
                    "characters. Duplicate operators are rejected.",
                ],
                [
                    "`BLITZE_API_KEY`",
                    "Single unnamed key, registered as operator `default`. "
                    "Also ≥ 32 characters.",
                ],
            ],
        ),
        "## Other variables read at startup",
        "",
        _table(
            ["Environment variable"],
            [[_cell(name)] for name in sorted(set(bare) - documented)],
        ),
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Ansible role reference
# --------------------------------------------------------------------------


def _describe_option(name: str, spec: dict[str, Any], default: object) -> list[str]:
    return [
        _cell(name),
        _cell(spec.get("type", "str")),
        _cell(spec.get("required", False)),
        _cell(spec.get("default", default)),
        _cell(spec.get("choices")) if spec.get("choices") else "—",
    ]


def render_roles() -> str:
    roles_dir = _edge_roles_dir()
    version = "unknown"
    manifest = roles_dir.parent / "MANIFEST.json"
    if manifest.is_file():
        version = json.loads(manifest.read_text(encoding="utf-8"))["collection_info"][
            "version"
        ]
    lines = [
        BANNER,
        "# Ansible role variables",
        "",
        f"Generated from **blitzecdn.edge {version}** — each role's",
        "`meta/argument_specs.yml` and `defaults/main.yml`. Roles validate these",
        "at the start of every run, so an unsupported value fails before the host",
        "is touched.",
        "",
        "Reference roles by their fully qualified name, for example",
        "`blitzecdn.edge.blitzecdn_nginx`. Set variables in the control plane's",
        "`ansible/inventory/group_vars/blitzecdn_edges.yml`. Ansible only",
        "auto-loads `group_vars` adjacent to the inventory file — a `group_vars/`",
        "directory anywhere else is silently ignored.",
        "",
    ]

    for role_dir in sorted(roles_dir.iterdir()):
        spec_file = role_dir / "meta/argument_specs.yml"
        if not spec_file.is_file():
            continue
        spec = yaml.safe_load(spec_file.read_text(encoding="utf-8")) or {}
        main = spec.get("argument_specs", {}).get("main", {})
        defaults_file = role_dir / "defaults/main.yml"
        defaults = (
            yaml.safe_load(defaults_file.read_text(encoding="utf-8")) or {}
            if defaults_file.is_file()
            else {}
        )

        lines.append(f"## `{role_dir.name}`")
        lines.append("")
        if main.get("short_description"):
            lines.extend([_text(main["short_description"]), ""])

        options = main.get("options", {})
        rows = [
            _describe_option(name, option or {}, defaults.get(name))
            for name, option in sorted(options.items())
        ]
        lines.append(_table(["Variable", "Type", "Required", "Default", "Choices"], rows))

        for name, option in sorted(options.items()):
            suboptions = (option or {}).get("options")
            if not suboptions:
                continue
            lines.append(f"### `{name}` element keys")
            lines.append("")
            lines.append(
                _table(
                    ["Key", "Type", "Required", "Default", "Choices"],
                    [
                        _describe_option(key, sub or {}, None)
                        for key, sub in sorted(suboptions.items())
                    ],
                )
            )

    return "\n".join(lines)


# --------------------------------------------------------------------------
# entrypoint
# --------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of writing when the committed output is stale.",
    )
    arguments = parser.parse_args()

    pages = {
        "api.mdx": render_api(build_openapi_schema()),
        "cli.mdx": render_cli(),
        "configuration.mdx": render_configuration(),
        "roles.mdx": render_roles(),
    }

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []
    for name, content in pages.items():
        target = OUTPUT_DIR / name
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current == content:
            continue
        if arguments.check:
            stale.append(name)
        else:
            target.write_text(content, encoding="utf-8")
            print(f"wrote {target.relative_to(WEB_DIR)}")

    if stale:
        print(
            "Generated reference is stale: "
            + ", ".join(stale)
            + "\nRun `npm run generate` in web/ and commit the result.",
            file=sys.stderr,
        )
        return 1
    if arguments.check:
        print("Generated reference is current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
